name: 1) Deploy to Dev
on:
  workflow_dispatch:
    inputs:
      pantheon_tag:
        description: 'Deploy to sites tagged:'
        required: true
        default: 'all'
env:
  INPUT_PANTHEON_TAG: ${{ github.event.inputs.pantheon_tag }}
jobs:
  build:
    name: Deploy code to Dev
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
    - uses: actions/checkout@v2
    # Install Terminus.
    - name: Install Terminus
      uses: pantheon-systems/terminus-github-actions@main
      with:
        pantheon-machine-token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
    - name: Parallel Processing
      env:
        ORG_UUID: ${{ secrets.ORG_UUID }}
        UPSTREAM_UUID: ${{ secrets.UPSTREAM_UUID }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      run: |
        if  [ $INPUT_PANTHEON_TAG == all ]
        then
          echo "Deploying all sites running this upstream."
          terminus org:site:list $ORG_UUID --format list --upstream $UPSTREAM_UUID --field name | sort -V | parallel --jobs 100 .github/scripts/dev-deploy.sh {}
        else
          echo "Deploying sites with tag: $INPUT_PANTHEON_TAG."
          terminus org:site:list $ORG_UUID --format list --upstream $UPSTREAM_UUID  --tag $INPUT_PANTHEON_TAG --field name | sort -V | parallel --jobs 100 .github/scripts/dev-deploy.sh {}
        fi